a = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('É alfanumérico? {}'.format(a.isalnum()))
print('É alfabético? {}'.format(a.isalpha()))
print('É decimal? {}'.format(a.isdecimal()))
print('É um digito? {}'.format(a.isdigit()))
print('É possivel identificar? {}'.format(a.isidentifier()))
print('Esta em caixa baixa? {}'.format(a.islower()))
print('É um numero? {}'.format(a.isnumeric()))
print('É possivel imprimi-lo? {}'.format(a.isprintable()))
print('Só tem espaço? {}'.format(a.isspace()))
print('Esta capitalizada? {}'.format(a.istitle()))
print('Esta em caixa alta? {}'.format(a.isupper()))