/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author igorv
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    TelaPagamento telaPagamento = new TelaPagamento();
    static ArrayList<Funcionario> listaFuncionarios = new ArrayList<>();
    static ArrayList<Cliente> listaCliente = new ArrayList<>();
    static ArrayList<Produto> listaProdutos = new ArrayList<>();
    static ArrayList<Venda> listaVendas = new ArrayList<>();
    private int codigo;
    float precoTotalVendaAvulsa;
    float precoTotalVendaCliente;

    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        telaVenda = new javax.swing.JTabbedPane();
        telaVendaAvulso = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigoProdutoVendaAvulsa = new javax.swing.JTextField();
        btnAdicionarProdutoVendaAvulsa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVendaAvulsa = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtQuantidadeProdutoVendaAvulsa = new javax.swing.JTextField();
        lblPreçoTotalVendaAvulsa = new javax.swing.JLabel();
        btnFinalizarVendaAvulso = new javax.swing.JButton();
        txtCodigoFuncioanarioVendaAvulsa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        telaVendaCliente = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbVendaCliente = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCodigoClienteVendaCliente = new javax.swing.JTextField();
        txtCodigoProdutoVendaCliente = new javax.swing.JTextField();
        txtQuantidadeProdutoVendaCliente = new javax.swing.JTextField();
        btnAdicionarProdutoVendaCliente = new javax.swing.JButton();
        lblPrecoTotalVendaCliente = new javax.swing.JLabel();
        btnFinalizarVendaCliente = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtCodigoFuncionarioVendaCliente = new javax.swing.JTextField();
        telaVendaEfetuadas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbVendasEfetuadas = new javax.swing.JTable();
        btnListarVenda = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtCodigoVenda = new javax.swing.JTextField();
        btnExibirProdutosVenda = new javax.swing.JButton();
        btnLimparVenda = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        telaCadastro = new javax.swing.JTabbedPane();
        telaCadastroCliente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        btnCadastrarCliente = new javax.swing.JButton();
        telaCadastroProduto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecoProduto = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        txtQuantidadeProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoProduto = new javax.swing.JTextArea();
        btnCadastrarProduto = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        estoque = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        visualizar = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtCodigoProdutoEstoque = new javax.swing.JTextField();
        btnBuscarProduto = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbEstoque = new javax.swing.JTable();
        btnLimpar = new javax.swing.JButton();
        atualizar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoProdutoAtualizar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtQuantidadeProdutoAtualizar = new javax.swing.JTextField();
        txtPrecoProdutoAtualizar = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescricaoProdutoAtualizar = new javax.swing.JTextArea();
        btnAtualizar = new javax.swing.JButton();
        produtoComBaixoEstoque = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbProdutoComBaixoEstoque = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnLimparBaixoEstoque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Código Produto");

        txtCodigoProdutoVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnAdicionarProdutoVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdicionarProdutoVendaAvulsa.setText("ADICIONAR");
        btnAdicionarProdutoVendaAvulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoVendaAvulsaActionPerformed(evt);
            }
        });

        tbVendaAvulsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Preço Unitario", "Quantidade", "Preço Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbVendaAvulsa);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Quantidade");

        txtQuantidadeProdutoVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblPreçoTotalVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPreçoTotalVendaAvulsa.setText("Preço Total");

        btnFinalizarVendaAvulso.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFinalizarVendaAvulso.setText("FINALIZAR");
        btnFinalizarVendaAvulso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaAvulsoActionPerformed(evt);
            }
        });

        txtCodigoFuncioanarioVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Código Funcionário");

        javax.swing.GroupLayout telaVendaAvulsoLayout = new javax.swing.GroupLayout(telaVendaAvulso);
        telaVendaAvulso.setLayout(telaVendaAvulsoLayout);
        telaVendaAvulsoLayout.setHorizontalGroup(
            telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                        .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtQuantidadeProdutoVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoProdutoVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarProdutoVendaAvulsa))
                    .addComponent(lblPreçoTotalVendaAvulsa)
                    .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoFuncioanarioVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(btnFinalizarVendaAvulso)))
                .addContainerGap(302, Short.MAX_VALUE))
        );
        telaVendaAvulsoLayout.setVerticalGroup(
            telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodigoProdutoVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtQuantidadeProdutoVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarProdutoVendaAvulsa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreçoTotalVendaAvulsa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCodigoFuncioanarioVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnFinalizarVendaAvulso)
                .addContainerGap())
        );

        telaVenda.addTab("VENDA AVULSO", telaVendaAvulso);

        tbVendaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Preço Unitario", "Quantidade", "Preço Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbVendaCliente);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Código Cliente");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Código Produto");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Quantidade");

        txtCodigoClienteVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtCodigoProdutoVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtQuantidadeProdutoVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnAdicionarProdutoVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdicionarProdutoVendaCliente.setText("ADICIONAR");
        btnAdicionarProdutoVendaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoVendaClienteActionPerformed(evt);
            }
        });

        lblPrecoTotalVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPrecoTotalVendaCliente.setText("Preço Total");

        btnFinalizarVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFinalizarVendaCliente.setText("FINALIZAR");
        btnFinalizarVendaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaClienteActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Código Funcionário");

        txtCodigoFuncionarioVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout telaVendaClienteLayout = new javax.swing.GroupLayout(telaVendaCliente);
        telaVendaCliente.setLayout(telaVendaClienteLayout);
        telaVendaClienteLayout.setHorizontalGroup(
            telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaVendaClienteLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 291, Short.MAX_VALUE))
            .addGroup(telaVendaClienteLayout.createSequentialGroup()
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecoTotalVendaCliente)
                    .addGroup(telaVendaClienteLayout.createSequentialGroup()
                        .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigoProdutoVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidadeProdutoVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarProdutoVendaCliente))
                    .addGroup(telaVendaClienteLayout.createSequentialGroup()
                        .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoClienteVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoFuncionarioVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(telaVendaClienteLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(btnFinalizarVendaCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaVendaClienteLayout.setVerticalGroup(
            telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaVendaClienteLayout.createSequentialGroup()
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCodigoProdutoVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtQuantidadeProdutoVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarProdutoVendaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecoTotalVendaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCodigoClienteVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCodigoFuncionarioVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarVendaCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        telaVenda.addTab("VENDA CLIENTE", telaVendaCliente);

        tbVendasEfetuadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Venda", "Tipo", "Cliente", "Funcionario", "Preço Total Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbVendasEfetuadas);

        btnListarVenda.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnListarVenda.setText("LISTAR VENDAS");
        btnListarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVendaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Código Venda");

        txtCodigoVenda.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnExibirProdutosVenda.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnExibirProdutosVenda.setText("EXIBIR PRODUTOS");

        btnLimparVenda.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLimparVenda.setText("LIMPAR");
        btnLimparVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaVendaEfetuadasLayout = new javax.swing.GroupLayout(telaVendaEfetuadas);
        telaVendaEfetuadas.setLayout(telaVendaEfetuadasLayout);
        telaVendaEfetuadasLayout.setHorizontalGroup(
            telaVendaEfetuadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
            .addGroup(telaVendaEfetuadasLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnListarVenda)
                .addGap(31, 31, 31)
                .addComponent(btnLimparVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(telaVendaEfetuadasLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExibirProdutosVenda)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        telaVendaEfetuadasLayout.setVerticalGroup(
            telaVendaEfetuadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaVendaEfetuadasLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaVendaEfetuadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListarVenda)
                    .addComponent(btnLimparVenda))
                .addGap(10, 10, 10)
                .addGroup(telaVendaEfetuadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExibirProdutosVenda))
                .addGap(35, 35, 35))
        );

        telaVenda.addTab("VENDAS EFETUADAS", telaVendaEfetuadas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaVenda)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaVenda)
        );

        telas.addTab("VENDA", jPanel1);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Codigo");

        txtNomeCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtCodigoCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCadastrarCliente.setText("CADASTRAR");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaCadastroClienteLayout = new javax.swing.GroupLayout(telaCadastroCliente);
        telaCadastroCliente.setLayout(telaCadastroClienteLayout);
        telaCadastroClienteLayout.setHorizontalGroup(
            telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarCliente)
                            .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 488, Short.MAX_VALUE))
        );
        telaCadastroClienteLayout.setVerticalGroup(
            telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarCliente)
                .addContainerGap(506, Short.MAX_VALUE))
        );

        telaCadastro.addTab("CLIENTE", telaCadastroCliente);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Codigo");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Preço");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Descrição");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Quantidade");

        txtPrecoProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoProdutoActionPerformed(evt);
            }
        });

        txtCodigoProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });

        txtQuantidadeProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtQuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeProdutoActionPerformed(evt);
            }
        });

        txtDescricaoProduto.setColumns(20);
        txtDescricaoProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDescricaoProduto.setRows(5);
        jScrollPane1.setViewportView(txtDescricaoProduto);

        btnCadastrarProduto.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCadastrarProduto.setText("CADASTRAR");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaCadastroProdutoLayout = new javax.swing.GroupLayout(telaCadastroProduto);
        telaCadastroProduto.setLayout(telaCadastroProdutoLayout);
        telaCadastroProdutoLayout.setHorizontalGroup(
            telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                            .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                                    .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                    .addGap(35, 35, 35))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCadastroProdutoLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtPrecoProduto)
                                .addComponent(txtQuantidadeProduto)))))
                .addGap(0, 457, Short.MAX_VALUE))
            .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnCadastrarProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaCadastroProdutoLayout.setVerticalGroup(
            telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(3, 3, 3)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarProduto)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        telaCadastro.addTab("PRODUTO", telaCadastroProduto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaCadastro)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaCadastro)
        );

        telas.addTab("CADASTRO", jPanel2);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("Código Produto");

        txtCodigoProdutoEstoque.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnBuscarProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBuscarProduto.setText("BUSCAR");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        tbEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Quantidade", "Preço Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tbEstoque);

        btnLimpar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout visualizarLayout = new javax.swing.GroupLayout(visualizar);
        visualizar.setLayout(visualizarLayout);
        visualizarLayout.setHorizontalGroup(
            visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizarLayout.createSequentialGroup()
                .addGroup(visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(visualizarLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar)
                        .addGap(0, 178, Short.MAX_VALUE))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        visualizarLayout.setVerticalGroup(
            visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visualizarLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(visualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtCodigoProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProduto)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(visualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        estoque.addTab("VISUALIZAR", jPanel4);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Código Produto");

        txtCodigoProdutoAtualizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Preço");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Quantidade");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Descrição");

        txtQuantidadeProdutoAtualizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtPrecoProdutoAtualizar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtDescricaoProdutoAtualizar.setColumns(20);
        txtDescricaoProdutoAtualizar.setRows(5);
        jScrollPane5.setViewportView(txtDescricaoProdutoAtualizar);

        btnAtualizar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnAtualizar.setText("ATUALIZAR");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout atualizarLayout = new javax.swing.GroupLayout(atualizar);
        atualizar.setLayout(atualizarLayout);
        atualizarLayout.setHorizontalGroup(
            atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atualizarLayout.createSequentialGroup()
                .addGroup(atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(atualizarLayout.createSequentialGroup()
                            .addGroup(atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel16))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtQuantidadeProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCodigoProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrecoProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(atualizarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnAtualizar)))
                .addContainerGap(463, Short.MAX_VALUE))
        );
        atualizarLayout.setVerticalGroup(
            atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atualizarLayout.createSequentialGroup()
                .addGroup(atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrecoProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(atualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantidadeProdutoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAtualizar)
                .addGap(0, 274, Short.MAX_VALUE))
        );

        estoque.addTab("ATUALIZAR", atualizar);

        tbProdutoComBaixoEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Quantidade", "Preço Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tbProdutoComBaixoEstoque);

        btnListar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnLimparBaixoEstoque.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnLimparBaixoEstoque.setText("LIMPAR");
        btnLimparBaixoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparBaixoEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout produtoComBaixoEstoqueLayout = new javax.swing.GroupLayout(produtoComBaixoEstoque);
        produtoComBaixoEstoque.setLayout(produtoComBaixoEstoqueLayout);
        produtoComBaixoEstoqueLayout.setHorizontalGroup(
            produtoComBaixoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
            .addGroup(produtoComBaixoEstoqueLayout.createSequentialGroup()
                .addComponent(btnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparBaixoEstoque)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        produtoComBaixoEstoqueLayout.setVerticalGroup(
            produtoComBaixoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produtoComBaixoEstoqueLayout.createSequentialGroup()
                .addGroup(produtoComBaixoEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar)
                    .addComponent(btnLimparBaixoEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        estoque.addTab("PRODUTOS COM BAIXO ESTOQUE", produtoComBaixoEstoque);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(estoque))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 681, Short.MAX_VALUE))
        );

        telas.addTab("ESTOQUE", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(telas, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telas, javax.swing.GroupLayout.PREFERRED_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        Produto produto = new Produto(Integer.parseInt(txtCodigoProduto.getText()), txtDescricaoProduto.getText(), Float.parseFloat(txtPrecoProduto.getText()), Integer.parseInt(txtQuantidadeProduto.getText()));
        try {
            BancoDeDados.SalvarProduto(produto);
        } catch (SQLException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        listaProdutos.add(produto);
        txtCodigoProduto.setText("");
        txtDescricaoProduto.setText("");
        txtPrecoProduto.setText("");
        txtQuantidadeProduto.setText("");
        TelaCadastroEfetuado telaCadastro = new TelaCadastroEfetuado();
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void txtQuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeProdutoActionPerformed

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    private void txtPrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoProdutoActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        Cliente cliente = new Cliente(txtNomeCliente.getText(), Integer.parseInt(txtCodigoCliente.getText()));
        listaCliente.add(cliente);
        try {
            BancoDeDados.SalvarCliente(cliente);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtNomeCliente.setText("");
        txtCodigoCliente.setText("");
        TelaCadastroEfetuado telaCadastro = new TelaCadastroEfetuado();
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void btnListarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVendaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbVendasEfetuadas.getModel();
        for (Venda venda : listaVendas) {
            Object[] informacoes = {venda.getCodigo(), venda.getTipo(), venda.getCliente(), venda.getFuncionario(), venda.getPreco()};
            model.addRow(informacoes);
        }
    }//GEN-LAST:event_btnListarVendaActionPerformed

    private void btnFinalizarVendaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaClienteActionPerformed
        codigo = listaVendas.size() + 1;
        for (Funcionario funcionario : listaFuncionarios) {
            for (Cliente cliente : listaCliente) {
                if (funcionario.getMatricula() == Integer.parseInt(txtCodigoFuncionarioVendaCliente.getText()) && (cliente.getCodigo() == Integer.parseInt(txtCodigoClienteVendaCliente.getText()))) {
                    Venda venda = new Venda(codigo, "Venda a Cliente", cliente.getNome(), funcionario.getNome(), precoTotalVendaCliente);
                    try {
                        BancoDeDados.SalvarVenda(venda);
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    listaVendas.add(venda);
                    TelaPagamento.precoTotalVenda = precoTotalVendaCliente;
                }
            }
        }
        telaPagamento.setLblPrcoTotalDinheiro(precoTotalVendaCliente);
        telaPagamento.setVisible(true);
        lblPrecoTotalVendaCliente.setVisible(false);
        txtCodigoFuncionarioVendaCliente.setText("");
        txtCodigoClienteVendaCliente.setText("");
        DefaultTableModel model = (DefaultTableModel) tbVendaCliente.getModel();
        for (int i = 0; i < tbVendaCliente.getRowCount(); i++) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnFinalizarVendaClienteActionPerformed

    private void btnAdicionarProdutoVendaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoVendaClienteActionPerformed
        boolean existe = false;
        for (Produto produto : listaProdutos) {
            if (produto.getCodigo() == Integer.parseInt(txtCodigoProdutoVendaCliente.getText())) {
                existe = true;
                if (produto.getQuantidade() >= Integer.parseInt(txtQuantidadeProdutoVendaCliente.getText())) {
                    DefaultTableModel model = (DefaultTableModel) tbVendaCliente.getModel();
                    float precoTotalProduto = Integer.parseInt(txtQuantidadeProdutoVendaCliente.getText()) * produto.getPreco();
                    Object[] informacoes = {produto.getCodigo(), produto.getPreco(), Integer.parseInt(txtQuantidadeProdutoVendaCliente.getText()), precoTotalProduto};
                    model.addRow(informacoes);
                    precoTotalVendaCliente = precoTotalVendaCliente + precoTotalProduto;
                    try (Formatter fmt = new Formatter()) {
                        fmt.format("%.2f", precoTotalVendaCliente);
                        lblPrecoTotalVendaCliente.setText("TOTAL = R$" + fmt);
                    }
                    produto.setQuantidade(produto.getQuantidade() - Integer.parseInt(txtQuantidadeProdutoVendaCliente.getText()));
                    try {
                        BancoDeDados.SalvarProduto(produto);
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    txtCodigoProdutoVendaCliente.setText("");
                    txtQuantidadeProdutoVendaCliente.setText("");
                } else {
                    TelaQuantidadeInsuficiente telaInsuficiente = new TelaQuantidadeInsuficiente();
                    telaInsuficiente.setVisible(true);
                    txtCodigoProdutoVendaCliente.setText("");
                    txtQuantidadeProdutoVendaCliente.setText("");
                }
            }
        }
        if (existe == false) {
            TelaProdutoNaoCadastrado tela = new TelaProdutoNaoCadastrado();
            tela.setVisible(true);
            txtCodigoProdutoVendaCliente.setText("");
            txtQuantidadeProdutoVendaCliente.setText("");
        }
    }//GEN-LAST:event_btnAdicionarProdutoVendaClienteActionPerformed

    private void btnFinalizarVendaAvulsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaAvulsoActionPerformed
        codigo = listaVendas.size() + 1;
        for (Funcionario funcionario : listaFuncionarios) {
            for (Cliente cliente : listaCliente) {
                if (cliente.getCodigo() == 0) {
                    if (funcionario.getMatricula() == Integer.parseInt(txtCodigoFuncioanarioVendaAvulsa.getText())) {
                        Venda venda = new Venda(codigo, "Venda Avulsa", cliente.getNome(), funcionario.getNome(), precoTotalVendaAvulsa);
                        try {
                            BancoDeDados.SalvarVenda(venda);
                        } catch (SQLException ex) {
                            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        listaVendas.add(venda);
                        TelaPagamento.precoTotalVenda = precoTotalVendaAvulsa;
                    }
                }
            }
        }
        telaPagamento.setLblPrcoTotalDinheiro(precoTotalVendaAvulsa);
        telaPagamento.setVisible(true);
        lblPreçoTotalVendaAvulsa.setVisible(false);
        txtCodigoFuncioanarioVendaAvulsa.setText("");
        DefaultTableModel model = (DefaultTableModel) tbVendaAvulsa.getModel();
        for (int i = 0; i < tbVendaAvulsa.getRowCount(); i++) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnFinalizarVendaAvulsoActionPerformed

    private void btnAdicionarProdutoVendaAvulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoVendaAvulsaActionPerformed
        boolean existe = false;
        for (Produto produto : listaProdutos) {
            if (produto.getCodigo() == Integer.parseInt(txtCodigoProdutoVendaAvulsa.getText())) {
                existe = true;
                if (produto.getQuantidade() >= Integer.parseInt(txtQuantidadeProdutoVendaAvulsa.getText())) {
                    DefaultTableModel model = (DefaultTableModel) tbVendaAvulsa.getModel();
                    float precoTotalProduto = Integer.parseInt(txtQuantidadeProdutoVendaAvulsa.getText()) * produto.getPreco();
                    Object[] informacoes = {produto.getCodigo(), produto.getPreco(), Integer.parseInt(txtQuantidadeProdutoVendaAvulsa.getText()), precoTotalProduto};
                    model.addRow(informacoes);
                    precoTotalVendaAvulsa = precoTotalVendaAvulsa + precoTotalProduto;
                    try (Formatter fmt = new Formatter()) {
                        fmt.format("%.2f", precoTotalVendaAvulsa);
                        lblPreçoTotalVendaAvulsa.setText("TOTAL = R$" + fmt);
                    }
                    produto.setQuantidade(produto.getQuantidade() - Integer.parseInt(txtQuantidadeProdutoVendaAvulsa.getText()));
                    try {
                        BancoDeDados.SalvarProduto(produto);
                    } catch (SQLException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    txtCodigoProdutoVendaAvulsa.setText("");
                    txtQuantidadeProdutoVendaAvulsa.setText("");
                } else {
                    TelaQuantidadeInsuficiente telaInsuficiente = new TelaQuantidadeInsuficiente();
                    telaInsuficiente.setVisible(true);
                    txtCodigoProdutoVendaAvulsa.setText("");
                    txtQuantidadeProdutoVendaAvulsa.setText("");
                }
            }
        }
        if (existe == false) {
            TelaProdutoNaoCadastrado tela = new TelaProdutoNaoCadastrado();
            tela.setVisible(true);
            txtCodigoProdutoVendaAvulsa.setText("");
            txtQuantidadeProdutoVendaAvulsa.setText("");
        }
    }//GEN-LAST:event_btnAdicionarProdutoVendaAvulsaActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        for (Produto produto : listaProdutos) {
            if (produto.getCodigo() == Integer.parseInt(txtCodigoProdutoEstoque.getText())) {
                DefaultTableModel model = (DefaultTableModel) tbEstoque.getModel();
                Object[] informacoes = {produto.getCodigo(), produto.getDescricao(), produto.getQuantidade(), produto.getPreco()};
                model.addRow(informacoes);
                txtCodigoProdutoEstoque.setText("");
            }
        }
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        for (Produto listaProduto : listaProdutos) {
            if (listaProduto.getCodigo() == Integer.parseInt(txtCodigoProdutoAtualizar.getText())) {
                if (!"".equals(txtQuantidadeProdutoAtualizar.getText())) {
                    listaProduto.setQuantidade(listaProduto.getQuantidade() + Integer.parseInt(txtQuantidadeProdutoAtualizar.getText()));
                }
                if (!"".equals(txtPrecoProdutoAtualizar.getText())) {
                    listaProduto.setPreco(Float.parseFloat(txtPrecoProdutoAtualizar.getText()));
                }
                if (!"".equals(txtDescricaoProdutoAtualizar.getText())) {
                    listaProduto.setDescricao(txtDescricaoProdutoAtualizar.getText());
                }
                try {
                    BancoDeDados.SalvarProduto(listaProduto);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                txtCodigoProdutoAtualizar.setText("");
                txtQuantidadeProdutoAtualizar.setText("");
                txtPrecoProdutoAtualizar.setText("");
                txtDescricaoProdutoAtualizar.setText("");
                TelaAtualizacaoRealizada tela = new TelaAtualizacaoRealizada();
                tela.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        for (Produto listaProduto : listaProdutos) {
            if (listaProduto.getQuantidade() < 10) {
                DefaultTableModel model = (DefaultTableModel) tbProdutoComBaixoEstoque.getModel();
                Object[] informacoes = {listaProduto.getCodigo(), listaProduto.getDescricao(), listaProduto.getQuantidade(), listaProduto.getPreco()};
                model.addRow(informacoes);
            }
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbEstoque.getModel();
        for (int i = 0; i < tbEstoque.getRowCount(); i++) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnLimparBaixoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparBaixoEstoqueActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbProdutoComBaixoEstoque.getModel();
        for (int i = 0; i < tbProdutoComBaixoEstoque.getRowCount(); i++) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnLimparBaixoEstoqueActionPerformed

    private void btnLimparVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparVendaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbVendasEfetuadas.getModel();
        for (int i = 0; i < tbVendasEfetuadas.getRowCount(); i++) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnLimparVendaActionPerformed

    public static ArrayList<Funcionario> getListaFuncionarios() {
        return listaFuncionarios;
    }

    public static void setListaFuncionarios(ArrayList<Funcionario> listaFuncionarios) {
        TelaPrincipal.listaFuncionarios = listaFuncionarios;
    }

    public static ArrayList<Cliente> getListaCliente() {
        return listaCliente;
    }

    public static void setListaCliente(ArrayList<Cliente> listaCliente) {
        TelaPrincipal.listaCliente = listaCliente;
    }

    public static ArrayList<Produto> getListaProdutos() {
        return listaProdutos;
    }

    public static void setListaProdutos(ArrayList<Produto> listaProdutos) {
        TelaPrincipal.listaProdutos = listaProdutos;
    }

    public static ArrayList<Venda> getListaVendas() {
        return listaVendas;
    }

    public static void setListaVendas(ArrayList<Venda> listaVendasAvulsas) {
        TelaPrincipal.listaVendas = listaVendasAvulsas;
    }

    public float getPrecoTotalVendaAvulsa() {
        return precoTotalVendaAvulsa;
    }

    public void setPrecoTotalVendaAvulsa(float precoTotalVenda) {
        this.precoTotalVendaAvulsa = precoTotalVenda;
    }

    public float getPrecoTotalVendaCliente() {
        return precoTotalVendaCliente;
    }

    public void setPrecoTotalVendaCliente(float precoTotalVendaCliente) {
        this.precoTotalVendaCliente = precoTotalVendaCliente;
    }

    public int getCodigo() {
        return codigo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atualizar;
    private javax.swing.JButton btnAdicionarProdutoVendaAvulsa;
    private javax.swing.JButton btnAdicionarProdutoVendaCliente;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnExibirProdutosVenda;
    private javax.swing.JButton btnFinalizarVendaAvulso;
    private javax.swing.JButton btnFinalizarVendaCliente;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparBaixoEstoque;
    private javax.swing.JButton btnLimparVenda;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListarVenda;
    private javax.swing.JTabbedPane estoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblPrecoTotalVendaCliente;
    private javax.swing.JLabel lblPreçoTotalVendaAvulsa;
    private javax.swing.JPanel produtoComBaixoEstoque;
    private javax.swing.JTable tbEstoque;
    private javax.swing.JTable tbProdutoComBaixoEstoque;
    private javax.swing.JTable tbVendaAvulsa;
    private javax.swing.JTable tbVendaCliente;
    private javax.swing.JTable tbVendasEfetuadas;
    private javax.swing.JTabbedPane telaCadastro;
    private javax.swing.JPanel telaCadastroCliente;
    private javax.swing.JPanel telaCadastroProduto;
    private javax.swing.JTabbedPane telaVenda;
    private javax.swing.JPanel telaVendaAvulso;
    private javax.swing.JPanel telaVendaCliente;
    private javax.swing.JPanel telaVendaEfetuadas;
    private javax.swing.JTabbedPane telas;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoClienteVendaCliente;
    private javax.swing.JTextField txtCodigoFuncioanarioVendaAvulsa;
    private javax.swing.JTextField txtCodigoFuncionarioVendaCliente;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtCodigoProdutoAtualizar;
    private javax.swing.JTextField txtCodigoProdutoEstoque;
    private javax.swing.JTextField txtCodigoProdutoVendaAvulsa;
    private javax.swing.JTextField txtCodigoProdutoVendaCliente;
    private javax.swing.JTextField txtCodigoVenda;
    private javax.swing.JTextArea txtDescricaoProduto;
    private javax.swing.JTextArea txtDescricaoProdutoAtualizar;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtPrecoProduto;
    private javax.swing.JTextField txtPrecoProdutoAtualizar;
    private javax.swing.JTextField txtQuantidadeProduto;
    private javax.swing.JTextField txtQuantidadeProdutoAtualizar;
    private javax.swing.JTextField txtQuantidadeProdutoVendaAvulsa;
    private javax.swing.JTextField txtQuantidadeProdutoVendaCliente;
    private javax.swing.JPanel visualizar;
    // End of variables declaration//GEN-END:variables
}
