/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import java.util.ArrayList;
import java.util.Formatter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author igorv
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaCliente
     */
    TelaPagamento telaPagamento = new TelaPagamento();
    ArrayList<Funcionario> listaFuncionarios = new ArrayList<>();
    ArrayList<Cliente> listaCliente = new ArrayList<>();
    ArrayList<Produto> listaProdutos = new ArrayList<>();
    ArrayList<Venda> listaVendasAvulsas = new ArrayList<>();
    ArrayList<Venda> listaVendasClientes = new ArrayList<>();
    private int codigo;
    float precoTotalVenda;
    float precoTotalVendaCliente;
    int x,z;

    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        telaVenda = new javax.swing.JTabbedPane();
        telaVendaAvulso = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigoProdutoVendaAvulsa = new javax.swing.JTextField();
        btnAdicionarProdutoVendaAvulsa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVendaAvulsa = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtQuantidadeProdutoVendaAvulsa = new javax.swing.JTextField();
        lblPreçoTotalVendaAvulsa = new javax.swing.JLabel();
        btnFinalizarVendaAvulso = new javax.swing.JButton();
        txtCodigoFuncioanarioVendaAvulsa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        telaVendaCliente = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbVendaCliente = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCodigoClienteVendaCliente = new javax.swing.JTextField();
        txtCodigoProdutoVendaCliente = new javax.swing.JTextField();
        txtQuantidadeProdutoVendaCliente = new javax.swing.JTextField();
        btnAdicionarProdutoVendaCliente = new javax.swing.JButton();
        lblPrecoTotalVendaCliente = new javax.swing.JLabel();
        btnFinalizarVendaCliente = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        txtCodigoFuncionarioVendaCliente = new javax.swing.JTextField();
        telaVendaEfetuadas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbVendasEfetuadas = new javax.swing.JTable();
        btnListarVenda = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtCodigoVenda = new javax.swing.JTextField();
        btnExibirProdutosVenda = new javax.swing.JButton();
        telaEstoque = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtCodigoProdutoEstoque = new javax.swing.JTextField();
        btnBuscarProduto = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbEstoque = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        telaCadastro = new javax.swing.JTabbedPane();
        telaCadastroFuncionario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMatriculaFuncionario = new javax.swing.JTextField();
        txtNomeFuncionario = new javax.swing.JTextField();
        txtSenhaFuncionario = new javax.swing.JPasswordField();
        btnCadastrarFuncionario = new javax.swing.JButton();
        telaCadastroCliente = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        btnCadastrarCliente = new javax.swing.JButton();
        telaCadastroProduto = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecoProduto = new javax.swing.JTextField();
        txtCodigoProduto = new javax.swing.JTextField();
        txtQuantidadeProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoProduto = new javax.swing.JTextArea();
        btnCadastrarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Código Produto");

        txtCodigoProdutoVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnAdicionarProdutoVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdicionarProdutoVendaAvulsa.setText("ADICIONAR");
        btnAdicionarProdutoVendaAvulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoVendaAvulsaActionPerformed(evt);
            }
        });

        tbVendaAvulsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Preço Unitario", "Quantidade", "Preço Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbVendaAvulsa);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Quantidade");

        txtQuantidadeProdutoVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lblPreçoTotalVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPreçoTotalVendaAvulsa.setText("Preço Total");

        btnFinalizarVendaAvulso.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFinalizarVendaAvulso.setText("FINALIZAR");
        btnFinalizarVendaAvulso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaAvulsoActionPerformed(evt);
            }
        });

        txtCodigoFuncioanarioVendaAvulsa.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Código Funcionário");

        javax.swing.GroupLayout telaVendaAvulsoLayout = new javax.swing.GroupLayout(telaVendaAvulso);
        telaVendaAvulso.setLayout(telaVendaAvulsoLayout);
        telaVendaAvulsoLayout.setHorizontalGroup(
            telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                        .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtQuantidadeProdutoVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoProdutoVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarProdutoVendaAvulsa))
                    .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnFinalizarVendaAvulso))
                    .addComponent(lblPreçoTotalVendaAvulsa)
                    .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoFuncioanarioVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        telaVendaAvulsoLayout.setVerticalGroup(
            telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaVendaAvulsoLayout.createSequentialGroup()
                .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodigoProdutoVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtQuantidadeProdutoVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarProdutoVendaAvulsa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreçoTotalVendaAvulsa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaAvulsoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCodigoFuncioanarioVendaAvulsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizarVendaAvulso))
        );

        telaVenda.addTab("VENDA AVULSO", telaVendaAvulso);

        tbVendaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Preço Unitario", "Quantidade", "Preço Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbVendaCliente);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Código Cliente");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Código Produto");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Quantidade");

        txtCodigoClienteVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtCodigoProdutoVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtQuantidadeProdutoVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnAdicionarProdutoVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdicionarProdutoVendaCliente.setText("ADICIONAR");
        btnAdicionarProdutoVendaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutoVendaClienteActionPerformed(evt);
            }
        });

        lblPrecoTotalVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblPrecoTotalVendaCliente.setText("Preço Total");

        btnFinalizarVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnFinalizarVendaCliente.setText("FINALIZAR");
        btnFinalizarVendaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarVendaClienteActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Código Funcionário");

        txtCodigoFuncionarioVendaCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        javax.swing.GroupLayout telaVendaClienteLayout = new javax.swing.GroupLayout(telaVendaCliente);
        telaVendaCliente.setLayout(telaVendaClienteLayout);
        telaVendaClienteLayout.setHorizontalGroup(
            telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaVendaClienteLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 219, Short.MAX_VALUE))
            .addGroup(telaVendaClienteLayout.createSequentialGroup()
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecoTotalVendaCliente)
                    .addGroup(telaVendaClienteLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnFinalizarVendaCliente))
                    .addGroup(telaVendaClienteLayout.createSequentialGroup()
                        .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigoProdutoVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantidadeProdutoVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionarProdutoVendaCliente))
                    .addGroup(telaVendaClienteLayout.createSequentialGroup()
                        .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoClienteVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoFuncionarioVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaVendaClienteLayout.setVerticalGroup(
            telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaVendaClienteLayout.createSequentialGroup()
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCodigoProdutoVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtQuantidadeProdutoVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarProdutoVendaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrecoTotalVendaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCodigoClienteVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaVendaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCodigoFuncionarioVendaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizarVendaCliente))
        );

        telaVenda.addTab("VENDA CLIENTE", telaVendaCliente);

        tbVendasEfetuadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Venda", "Cliente", "Fucnionario", "Preço Total Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbVendasEfetuadas);

        btnListarVenda.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnListarVenda.setText("LISTAR VENDAS");
        btnListarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVendaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("Código Venda");

        txtCodigoVenda.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnExibirProdutosVenda.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnExibirProdutosVenda.setText("EXIBIR PRODUTOS");

        javax.swing.GroupLayout telaVendaEfetuadasLayout = new javax.swing.GroupLayout(telaVendaEfetuadas);
        telaVendaEfetuadas.setLayout(telaVendaEfetuadasLayout);
        telaVendaEfetuadasLayout.setHorizontalGroup(
            telaVendaEfetuadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addGroup(telaVendaEfetuadasLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExibirProdutosVenda)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(telaVendaEfetuadasLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnListarVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaVendaEfetuadasLayout.setVerticalGroup(
            telaVendaEfetuadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaVendaEfetuadasLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarVenda)
                .addGap(29, 29, 29)
                .addGroup(telaVendaEfetuadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExibirProdutosVenda))
                .addGap(18, 18, 18))
        );

        telaVenda.addTab("VENDAS EFETUADAS", telaVendaEfetuadas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaVenda)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaVenda)
        );

        telas.addTab("VENDA", jPanel1);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Código Produto");

        txtCodigoProdutoEstoque.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnBuscarProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnBuscarProduto.setText("BUSCAR");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        tbEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descrição", "Quantidade", "Preço Unitario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbEstoque);

        javax.swing.GroupLayout telaEstoqueLayout = new javax.swing.GroupLayout(telaEstoque);
        telaEstoque.setLayout(telaEstoqueLayout);
        telaEstoqueLayout.setHorizontalGroup(
            telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaEstoqueLayout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProduto)
                .addGap(0, 243, Short.MAX_VALUE))
            .addComponent(jScrollPane5)
        );
        telaEstoqueLayout.setVerticalGroup(
            telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaEstoqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaEstoqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtCodigoProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
        );

        telas.addTab("ESTOQUE", telaEstoque);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Matricula");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Senha");

        txtMatriculaFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtNomeFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtSenhaFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnCadastrarFuncionario.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCadastrarFuncionario.setText("CADASTRAR");
        btnCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaCadastroFuncionarioLayout = new javax.swing.GroupLayout(telaCadastroFuncionario);
        telaCadastroFuncionario.setLayout(telaCadastroFuncionarioLayout);
        telaCadastroFuncionarioLayout.setHorizontalGroup(
            telaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroFuncionarioLayout.createSequentialGroup()
                .addGroup(telaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroFuncionarioLayout.createSequentialGroup()
                        .addGroup(telaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(telaCadastroFuncionarioLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnCadastrarFuncionario)))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        telaCadastroFuncionarioLayout.setVerticalGroup(
            telaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroFuncionarioLayout.createSequentialGroup()
                .addGroup(telaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMatriculaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addComponent(btnCadastrarFuncionario)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        telaCadastro.addTab("FUNCIONARIO", telaCadastroFuncionario);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Codigo");

        txtNomeCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        txtCodigoCliente.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoClienteActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCadastrarCliente.setText("CADASTRAR");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaCadastroClienteLayout = new javax.swing.GroupLayout(telaCadastroCliente);
        telaCadastroCliente.setLayout(telaCadastroClienteLayout);
        telaCadastroClienteLayout.setHorizontalGroup(
            telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrarCliente)
                            .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 416, Short.MAX_VALUE))
        );
        telaCadastroClienteLayout.setVerticalGroup(
            telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroClienteLayout.createSequentialGroup()
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarCliente)
                .addContainerGap(498, Short.MAX_VALUE))
        );

        telaCadastro.addTab("CLIENTE", telaCadastroCliente);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Codigo");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Preço");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Descrição");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Quantidade");

        txtPrecoProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPrecoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoProdutoActionPerformed(evt);
            }
        });

        txtCodigoProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });

        txtQuantidadeProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtQuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeProdutoActionPerformed(evt);
            }
        });

        txtDescricaoProduto.setColumns(20);
        txtDescricaoProduto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtDescricaoProduto.setRows(5);
        jScrollPane1.setViewportView(txtDescricaoProduto);

        btnCadastrarProduto.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCadastrarProduto.setText("CADASTRAR");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaCadastroProdutoLayout = new javax.swing.GroupLayout(telaCadastroProduto);
        telaCadastroProduto.setLayout(telaCadastroProdutoLayout);
        telaCadastroProdutoLayout.setHorizontalGroup(
            telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                            .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                                    .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6))
                                    .addGap(35, 35, 35))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCadastroProdutoLayout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtPrecoProduto)
                                .addComponent(txtQuantidadeProduto)))))
                .addGap(0, 385, Short.MAX_VALUE))
            .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnCadastrarProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaCadastroProdutoLayout.setVerticalGroup(
            telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroProdutoLayout.createSequentialGroup()
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(telaCadastroProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(3, 3, 3)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarProduto)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        telaCadastro.addTab("PRODUTO", telaCadastroProduto);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaCadastro)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telaCadastro)
        );

        telas.addTab("CADASTRO", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoProdutoActionPerformed

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    private void txtQuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeProdutoActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed
        Produto produto = new Produto(Integer.parseInt(txtCodigoProduto.getText()), txtDescricaoProduto.getText(), Float.parseFloat(txtPrecoProduto.getText()), Integer.parseInt(txtQuantidadeProduto.getText()));
        listaProdutos.add(produto);
        TelaCadastroEfetuado telaCadastro = new TelaCadastroEfetuado();
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void txtCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoClienteActionPerformed

    private void btnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioActionPerformed
        Funcionario funcionario = new Funcionario(Integer.parseInt(txtMatriculaFuncionario.getText()), txtNomeFuncionario.getText(), txtSenhaFuncionario.getText());
        listaFuncionarios.add(funcionario);
        TelaCadastroEfetuado telaCadastro = new TelaCadastroEfetuado();
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastrarFuncionarioActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        Cliente cliente = new Cliente(txtNomeCliente.getText(), Integer.parseInt(txtCodigoCliente.getText()));
        listaCliente.add(cliente);
        TelaCadastroEfetuado telaCadastro = new TelaCadastroEfetuado();
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        for (Produto produto : listaProdutos) {
            if (produto.getCodigo() == Integer.parseInt(txtCodigoProdutoEstoque.getText())) {
                DefaultTableModel model = (DefaultTableModel) tbEstoque.getModel();
                Object[] informacoes = {produto.getCodigo(), produto.getDescricao(), produto.getQuantidade(), produto.getPreço()};
                model.addRow(informacoes);
            }
        }
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnAdicionarProdutoVendaAvulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoVendaAvulsaActionPerformed
        boolean existe = false;
        for (Produto produto : listaProdutos) {
            if (produto.getCodigo() == Integer.parseInt(txtCodigoProdutoVendaAvulsa.getText())) {
                existe = true;
                if (produto.getQuantidade() >= Integer.parseInt(txtQuantidadeProdutoVendaAvulsa.getText())) {
                    DefaultTableModel model = (DefaultTableModel) tbVendaAvulsa.getModel();
                    float precoTotalProduto = Integer.parseInt(txtQuantidadeProdutoVendaAvulsa.getText()) * produto.getPreço();
                    Object[] informacoes = {produto.getCodigo(), produto.getPreço(), Integer.parseInt(txtQuantidadeProdutoVendaAvulsa.getText()), precoTotalProduto};
                    model.addRow(informacoes);
                    x = x + 1;
                    precoTotalVenda = precoTotalVenda + precoTotalProduto;
                    Formatter fmt = new Formatter();
                    fmt.format("%.2f", precoTotalVenda);
                    lblPreçoTotalVendaAvulsa.setText("TOTAL = R$" + fmt);
                    fmt.close();
                    txtCodigoProdutoVendaAvulsa.setText("");
                    txtQuantidadeProdutoVendaAvulsa.setText("");
                } else {
                    TelaQuantidadeInsuficiente telaInsuficiente = new TelaQuantidadeInsuficiente();
                    telaInsuficiente.setVisible(true);
                    txtCodigoProdutoVendaAvulsa.setText("");
                    txtQuantidadeProdutoVendaAvulsa.setText("");
                }
            }
        }
        if (existe == false) {
            TelaProdutoNaoCadastrado tela = new TelaProdutoNaoCadastrado();
            tela.setVisible(true);
            txtCodigoProdutoVendaAvulsa.setText("");
            txtQuantidadeProdutoVendaAvulsa.setText("");
        }
    }//GEN-LAST:event_btnAdicionarProdutoVendaAvulsaActionPerformed

    private void btnFinalizarVendaAvulsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaAvulsoActionPerformed
        codigo = listaVendasAvulsas.size() + 1;
        for (Funcionario funcionario : listaFuncionarios) {
            if (funcionario.getMatricula() == Integer.parseInt(txtCodigoFuncioanarioVendaAvulsa.getText())) {
                Venda venda = new Venda(codigo, funcionario, precoTotalVenda);
                listaVendasAvulsas.add(venda);
                telaPagamento.precoTotalVenda = precoTotalVenda;
            }
        }
        telaPagamento.setLblPrcoTotalDinheiro(precoTotalVenda);
        telaPagamento.setVisible(true);
        lblPreçoTotalVendaAvulsa.setVisible(false);
        txtCodigoFuncioanarioVendaAvulsa.setText("");
        DefaultTableModel model = (DefaultTableModel) tbVendaAvulsa.getModel();
        for (int i = 0; i < x; i++) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnFinalizarVendaAvulsoActionPerformed

    private void btnListarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVendaActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbVendasEfetuadas.getModel();
        for (Venda venda : listaVendasClientes) {
            Object[] informacoes = {venda.getCodigo(), venda.getCliente().getNome(), venda.getFuncionario().getNome(), venda.getPreco()};
            model.addRow(informacoes);
        }
        for (Venda venda : listaVendasAvulsas) {
            Object[] informacoes = {venda.getCodigo(), "Venda Avulsa", venda.getFuncionario().getNome(), venda.getPreco()};
            model.addRow(informacoes);
        }
    }//GEN-LAST:event_btnListarVendaActionPerformed

    private void btnAdicionarProdutoVendaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutoVendaClienteActionPerformed
        boolean existe = false;
        for (Produto produto : listaProdutos) {
            if (produto.getCodigo() == Integer.parseInt(txtCodigoProdutoVendaCliente.getText())) {
                existe = true;
                if (produto.getQuantidade() >= Integer.parseInt(txtQuantidadeProdutoVendaCliente.getText())) {
                    DefaultTableModel model = (DefaultTableModel) tbVendaCliente.getModel();
                    float precoTotalProduto = Integer.parseInt(txtQuantidadeProdutoVendaCliente.getText()) * produto.getPreço();
                    Object[] informacoes = {produto.getCodigo(), produto.getPreço(), Integer.parseInt(txtQuantidadeProdutoVendaCliente.getText()), precoTotalProduto};
                    model.addRow(informacoes);
                    z = z + 1;
                    precoTotalVendaCliente = precoTotalVendaCliente + precoTotalProduto;
                    Formatter fmt = new Formatter();
                    fmt.format("%.2f", precoTotalVendaCliente);
                    lblPrecoTotalVendaCliente.setText("TOTAL = R$" + fmt);
                    fmt.close();
                    txtCodigoProdutoVendaCliente.setText("");
                    txtQuantidadeProdutoVendaCliente.setText("");
                } else {
                    TelaQuantidadeInsuficiente telaInsuficiente = new TelaQuantidadeInsuficiente();
                    telaInsuficiente.setVisible(true);
                    txtCodigoProdutoVendaCliente.setText("");
                    txtQuantidadeProdutoVendaCliente.setText("");
                }
            }
        }
        if (existe == false) {
            TelaProdutoNaoCadastrado tela = new TelaProdutoNaoCadastrado();
            tela.setVisible(true);
            txtCodigoProdutoVendaCliente.setText("");
            txtQuantidadeProdutoVendaCliente.setText("");
        }
    }//GEN-LAST:event_btnAdicionarProdutoVendaClienteActionPerformed

    private void btnFinalizarVendaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarVendaClienteActionPerformed
        codigo = listaVendasAvulsas.size() + 1;
        for (Funcionario funcionario : listaFuncionarios) {
            for (Cliente cliente : listaCliente) {
                if (funcionario.getMatricula() == Integer.parseInt(txtCodigoFuncionarioVendaCliente.getText()) && (cliente.getCodigo() == Integer.parseInt(txtCodigoClienteVendaCliente.getText()))) {
                    Venda venda = new Venda(codigo, cliente, funcionario, precoTotalVendaCliente);
                    listaVendasClientes.add(venda);
                    telaPagamento.precoTotalVenda = precoTotalVendaCliente;
                }
            }
        }
        telaPagamento.setLblPrcoTotalDinheiro(precoTotalVendaCliente);
        telaPagamento.setVisible(true);
        lblPrecoTotalVendaCliente.setVisible(false);
        txtCodigoFuncionarioVendaCliente.setText("");
        txtCodigoClienteVendaCliente.setText("");
        DefaultTableModel model = (DefaultTableModel) tbVendaCliente.getModel();
        for (int i = 0; i < z; i++) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnFinalizarVendaClienteActionPerformed

    public ArrayList<Funcionario> getListafuncionarios() {
        return listaFuncionarios;
    }

    public ArrayList<Cliente> getListacliente() {
        return listaCliente;
    }

    public ArrayList<Produto> getListaprodutos() {
        return listaProdutos;
    }

    public ArrayList<Venda> getListaVendasAvulsas() {
        return listaVendasAvulsas;
    }

    public ArrayList<Venda> getListaVendasClientes() {
        return listaVendasClientes;
    }

    public int getCodigo() {
        return codigo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProdutoVendaAvulsa;
    private javax.swing.JButton btnAdicionarProdutoVendaCliente;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCadastrarFuncionario;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnExibirProdutosVenda;
    private javax.swing.JButton btnFinalizarVendaAvulso;
    private javax.swing.JButton btnFinalizarVendaCliente;
    private javax.swing.JButton btnListarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblPrecoTotalVendaCliente;
    private javax.swing.JLabel lblPreçoTotalVendaAvulsa;
    private javax.swing.JTable tbEstoque;
    private javax.swing.JTable tbVendaAvulsa;
    private javax.swing.JTable tbVendaCliente;
    private javax.swing.JTable tbVendasEfetuadas;
    private javax.swing.JTabbedPane telaCadastro;
    private javax.swing.JPanel telaCadastroCliente;
    private javax.swing.JPanel telaCadastroFuncionario;
    private javax.swing.JPanel telaCadastroProduto;
    private javax.swing.JPanel telaEstoque;
    private javax.swing.JTabbedPane telaVenda;
    private javax.swing.JPanel telaVendaAvulso;
    private javax.swing.JPanel telaVendaCliente;
    private javax.swing.JPanel telaVendaEfetuadas;
    private javax.swing.JTabbedPane telas;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtCodigoClienteVendaCliente;
    private javax.swing.JTextField txtCodigoFuncioanarioVendaAvulsa;
    private javax.swing.JTextField txtCodigoFuncionarioVendaCliente;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtCodigoProdutoEstoque;
    private javax.swing.JTextField txtCodigoProdutoVendaAvulsa;
    private javax.swing.JTextField txtCodigoProdutoVendaCliente;
    private javax.swing.JTextField txtCodigoVenda;
    private javax.swing.JTextArea txtDescricaoProduto;
    private javax.swing.JTextField txtMatriculaFuncionario;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeFuncionario;
    private javax.swing.JTextField txtPrecoProduto;
    private javax.swing.JTextField txtQuantidadeProduto;
    private javax.swing.JTextField txtQuantidadeProdutoVendaAvulsa;
    private javax.swing.JTextField txtQuantidadeProdutoVendaCliente;
    private javax.swing.JPasswordField txtSenhaFuncionario;
    // End of variables declaration//GEN-END:variables
}
