/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AluguelControl;
import controller.ItemControl;
import controller.MainControl;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;

/**
 *
 * @author igorv
 */
public class AluguelView extends javax.swing.JFrame {

    /**
     * Creates new form Aluguel
     */
    private int idItem;
    private String dataItem;
    private String produtoraItem;
    private float valorItem;
    private String midiaItem;
    @SuppressWarnings("LeakingThisInConstructor")
    public AluguelView() {
        initComponents();
        AluguelControl.LimparComboBox(this);
        try {
            AluguelControl.CarregarDadosMidia(this);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(AluguelView.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            AluguelControl.CarregarDadosProdutora(this);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(AluguelView.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblFiltrarPorSituação.setVisible(false);
        cbFiltrarPorSituacao.setVisible(false);
        tpCdSelecionado.setVisible(false);
        lblFiltrarPorProdutora.setVisible(false);
        cbFiltrarPorProdutora.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        cbTipoDeMidia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItens = new javax.swing.JTable();
        tpCdSelecionado = new javax.swing.JTabbedPane();
        pnCdSelecionado = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblItemEscolhido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuantidadeDias = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDataDevolucao = new javax.swing.JFormattedTextField();
        btnSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtCpfCliente = new javax.swing.JTextField();
        lblFiltrarPorSituação = new javax.swing.JLabel();
        cbFiltrarPorSituacao = new javax.swing.JComboBox<>();
        btnSair = new javax.swing.JButton();
        lblFiltrarPorProdutora = new javax.swing.JLabel();
        cbFiltrarPorProdutora = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Tipo de Mídia:");

        cbTipoDeMidia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbTipoDeMidia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        cbTipoDeMidia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbTipoDeMidiaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbTipoDeMidiaMousePressed(evt);
            }
        });
        cbTipoDeMidia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDeMidiaActionPerformed(evt);
            }
        });

        tbItens.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tbItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "ID", "Descrição", "Valor", "Situação", "Midia", "Produtora", "Data Compra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbItens);

        tpCdSelecionado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Item Escolhido:");

        lblItemEscolhido.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblItemEscolhido.setText("Exemplo");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Quantidade Dias:");

        txtQuantidadeDias.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtQuantidadeDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeDiasActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Data Devolução:");

        txtDataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataDevolucao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        btnSalvar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("CPF Cliente:");

        txtCpfCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCdSelecionadoLayout = new javax.swing.GroupLayout(pnCdSelecionado);
        pnCdSelecionado.setLayout(pnCdSelecionadoLayout);
        pnCdSelecionadoLayout.setHorizontalGroup(
            pnCdSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCdSelecionadoLayout.createSequentialGroup()
                .addGroup(pnCdSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCdSelecionadoLayout.createSequentialGroup()
                        .addGroup(pnCdSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnCdSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemEscolhido, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnCdSelecionadoLayout.createSequentialGroup()
                                .addComponent(txtQuantidadeDias, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnCdSelecionadoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 272, Short.MAX_VALUE))
            .addGroup(pnCdSelecionadoLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(btnSalvar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCdSelecionadoLayout.setVerticalGroup(
            pnCdSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCdSelecionadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCdSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblItemEscolhido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCdSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantidadeDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnCdSelecionadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addContainerGap())
        );

        tpCdSelecionado.addTab("Cd Selecionado", pnCdSelecionado);

        lblFiltrarPorSituação.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFiltrarPorSituação.setText("Filtrar por Situação:");

        cbFiltrarPorSituacao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbFiltrarPorSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "D", "A" }));
        cbFiltrarPorSituacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbFiltrarPorSituacaoMouseClicked(evt);
            }
        });
        cbFiltrarPorSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltrarPorSituacaoActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblFiltrarPorProdutora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblFiltrarPorProdutora.setText("Filtrar por Produtora:");

        cbFiltrarPorProdutora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cbFiltrarPorProdutora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar" }));
        cbFiltrarPorProdutora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbFiltrarPorProdutoraMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbFiltrarPorProdutoraMousePressed(evt);
            }
        });
        cbFiltrarPorProdutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltrarPorProdutoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFiltrarPorSituação)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltrarPorSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tpCdSelecionado)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(cbTipoDeMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFiltrarPorProdutora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltrarPorProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbTipoDeMidia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFiltrarPorProdutora)
                            .addComponent(cbFiltrarPorProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltrarPorSituação)
                    .addComponent(cbFiltrarPorSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(tpCdSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantidadeDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeDiasActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Date data = new Date();
        Date dataDevolucao = AluguelControl.FormatarData(txtDataDevolucao.getText());
        float valor = 0;
        try {
            valor = AluguelControl.CarcularValor(Integer.parseInt(txtQuantidadeDias.getText()), lblItemEscolhido.getText());
        } catch (SQLException | IOException ex) {
            Logger.getLogger(AluguelView.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            AluguelControl.SalvarAluguel(Integer.parseInt(txtCpfCliente.getText()), lblItemEscolhido.getText(), "A", data, dataDevolucao, valor);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(AluguelView.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ItemControl.Atualizar(getIdItem(), getLblItemEscolhido().getText(), getDataItem(), getProdutoraItem(), "A", getValorItem(), getMidiaItem());
        } catch (SQLException | IOException | ParseException ex) {
            Logger.getLogger(AluguelView.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Aluguel realizado");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfClienteActionPerformed

    private void tbItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItensMouseClicked
        int linha = tbItens.getSelectedRow();
        AluguelControl.ItemSelecionado(this, linha);
        getTpCdSelecionado().setVisible(true);
    }//GEN-LAST:event_tbItensMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        MainControl.AcessarMenu();
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void cbTipoDeMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDeMidiaActionPerformed
        
    }//GEN-LAST:event_cbTipoDeMidiaActionPerformed

    private void cbFiltrarPorSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltrarPorSituacaoActionPerformed
        
    }//GEN-LAST:event_cbFiltrarPorSituacaoActionPerformed

    private void cbTipoDeMidiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoDeMidiaMouseClicked
        AluguelControl.LimparTabela(this);
        try {
            AluguelControl.FiltroMidia(this, cbTipoDeMidia.getSelectedItem().toString());
        } catch (SQLException | IOException ex) {
            Logger.getLogger(AluguelView.class.getName()).log(Level.SEVERE, null, ex);
        }
        getLblFiltrarPorProdutora().setVisible(true);
        getCbFiltrarPorProdutora().setVisible(true);  
    }//GEN-LAST:event_cbTipoDeMidiaMouseClicked

    private void cbFiltrarPorSituacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFiltrarPorSituacaoMouseClicked
        AluguelControl.LimparTabela(this);
        try {
            AluguelControl.FiltroSituacao(this, cbFiltrarPorSituacao.getSelectedItem().toString(), cbTipoDeMidia.getSelectedItem().toString(), cbFiltrarPorProdutora.getSelectedItem().toString());
        } catch (SQLException | IOException ex) {
            Logger.getLogger(AluguelView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbFiltrarPorSituacaoMouseClicked

    private void cbTipoDeMidiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbTipoDeMidiaMousePressed
          
    }//GEN-LAST:event_cbTipoDeMidiaMousePressed

    private void cbFiltrarPorProdutoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFiltrarPorProdutoraMouseClicked
        AluguelControl.LimparTabela(this);
        try {
            AluguelControl.FiltroProdutora(this, cbFiltrarPorProdutora.getSelectedItem().toString(), cbTipoDeMidia.getSelectedItem().toString());
        } catch (SQLException | IOException ex) {
            Logger.getLogger(AluguelView.class.getName()).log(Level.SEVERE, null, ex);
        }
        getLblFiltrarPorSituação().setVisible(true);
        getCbFiltrarPorSituacao().setVisible(true);
    }//GEN-LAST:event_cbFiltrarPorProdutoraMouseClicked

    private void cbFiltrarPorProdutoraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbFiltrarPorProdutoraMousePressed
        
    }//GEN-LAST:event_cbFiltrarPorProdutoraMousePressed

    private void cbFiltrarPorProdutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltrarPorProdutoraActionPerformed
        
    }//GEN-LAST:event_cbFiltrarPorProdutoraActionPerformed

    public JTabbedPane getTpCdSelecionado() {
        return tpCdSelecionado;
    }

    public void setTpCdSelecionado(JTabbedPane tpCdSelecionado) {
        this.tpCdSelecionado = tpCdSelecionado;
    }

    public JLabel getLblItemEscolhido() {
        return lblItemEscolhido;
    }

    public void setLblItemEscolhido(JLabel lblItemEscolhido) {
        this.lblItemEscolhido = lblItemEscolhido;
    }

    public JTable getTbItens() {
        return tbItens;
    }

    public void setTbItens(JTable tbItens) {
        this.tbItens = tbItens;
    }

    public JComboBox<String> getCbFiltrarPorSituacao() {
        return cbFiltrarPorSituacao;
    }

    public void setCbFiltrarPorSituacao(JComboBox<String> cbFiltrarPorSituacao) {
        this.cbFiltrarPorSituacao = cbFiltrarPorSituacao;
    }

    public JComboBox<String> getCbTipoDeMidia() {
        return cbTipoDeMidia;
    }

    public void setCbTipoDeMidia(JComboBox<String> cbTipoDeMidia) {
        this.cbTipoDeMidia = cbTipoDeMidia;
    }

    public JLabel getLblFiltrarPorSituação() {
        return lblFiltrarPorSituação;
    }

    public void setLblFiltrarPorSituação(JLabel lblFiltrarPorSituação) {
        this.lblFiltrarPorSituação = lblFiltrarPorSituação;
    }

    public JComboBox<String> getCbFiltrarPorProdutora() {
        return cbFiltrarPorProdutora;
    }

    public void setCbFiltrarPorProdutora(JComboBox<String> cbFiltrarPorProdutora) {
        this.cbFiltrarPorProdutora = cbFiltrarPorProdutora;
    }

    public JLabel getLblFiltrarPorProdutora() {
        return lblFiltrarPorProdutora;
    }

    public void setLblFiltrarPorProdutora(JLabel lblFiltrarPorProdutora) {
        this.lblFiltrarPorProdutora = lblFiltrarPorProdutora;
    }

    public int getIdItem() {
        return idItem;
    }

    public void setIdItem(int idItem) {
        this.idItem = idItem;
    } 

    public String getDataItem() {
        return dataItem;
    }

    public void setDataItem(String dataItem) {
        this.dataItem = dataItem;
    }

    public String getProdutoraItem() {
        return produtoraItem;
    }

    public void setProdutoraItem(String produtoraItem) {
        this.produtoraItem = produtoraItem;
    }

    public float getValorItem() {
        return valorItem;
    }

    public void setValorItem(float valorItem) {
        this.valorItem = valorItem;
    }

    public String getMidiaItem() {
        return midiaItem;
    }

    public void setMidiaItem(String midiaItem) {
        this.midiaItem = midiaItem;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AluguelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AluguelView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbFiltrarPorProdutora;
    private javax.swing.JComboBox<String> cbFiltrarPorSituacao;
    private javax.swing.JComboBox<String> cbTipoDeMidia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFiltrarPorProdutora;
    private javax.swing.JLabel lblFiltrarPorSituação;
    private javax.swing.JLabel lblItemEscolhido;
    private javax.swing.JPanel pnCdSelecionado;
    private javax.swing.JTable tbItens;
    private javax.swing.JTabbedPane tpCdSelecionado;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JFormattedTextField txtDataDevolucao;
    private javax.swing.JTextField txtQuantidadeDias;
    // End of variables declaration//GEN-END:variables
}
